# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b65c0b005166ad78d63ce70fd92e23245819c5f2945a02300b6b4ee8362b0476591d0e117b31d63b80607ef18033849b018464d3bd4cf91e7ab0304c0ded6f9

test:
  secret_key_base: 1640a74998903c12729a77109e46c3b3d6171fd1ffb6595ecaec7dea37e4e9c48f60297c5f0762ffbaa280286513d52e7217f48cbd915a35214e466de1fa9edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
